module.exports = {
  darkMode: "class",
  content: ["./code.html"],
  theme: {
    extend: {
      colors: {
        background: "#f9f9f9",
        "primary-fixed-dim": "#71de5d",
        "primary-fixed": "#8cfc76",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#930007",
        "on-tertiary-container": "#f6f3f3",
        "surface-dim": "#dadada",
        "on-secondary-container": "#fffbff",
        "inverse-primary": "#71de5d",
        error: "#ba1a1a",
        "surface-variant": "#e2e2e2",
        "on-tertiary-fixed-variant": "#474746",
        "tertiary-fixed": "#e5e2e1",
        "on-primary-fixed": "#002200",
        "on-surface-variant": "#3f4a3a",
        "inverse-on-surface": "#f1f1f1",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-container-highest": "#e2e2e2",
        "on-error": "#ffffff",
        "primary-container": "#008200",
        "secondary-container": "#e80f16",
        "outline-variant": "#becab6",
        "on-tertiary": "#ffffff",
        primary: "#006600",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006e00",
        "secondary-fixed-dim": "#ffb4aa",
        "secondary-fixed": "#ffdad5",
        "on-primary-container": "#d8ffc8",
        "on-error-container": "#93000a",
        "surface-container-high": "#e8e8e8",
        outline: "#6f7b69",
        "inverse-surface": "#2f3131",
        surface: "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "surface-container": "#eeeeee",
        "on-primary-fixed-variant": "#005300",
        tertiary: "#575757",
        "on-surface": "#1a1c1c",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1c",
        secondary: "#bc000c",
        "tertiary-container": "#706f6f",
        "on-secondary-fixed": "#410001"
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: { xl: "48px", xs: "4px", unit: "4px", sm: "8px", lg: "24px", "container-max": "1280px", md: "16px", gutter: "24px" },
      fontFamily: {
        "headline-md": ["Be Vietnam Pro"],
        "label-sm": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "headline-lg": ["Be Vietnam Pro"],
        "body-md": ["Be Vietnam Pro"],
        "label-bold": ["Be Vietnam Pro"],
        "display-lg": ["Be Vietnam Pro"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    }
  },
  plugins: []
};
